{
 "title": "HTTP Server Projeto Korp - Dashboard",
 "tags": [
  "korp",
  "devops",
  "prometheus",
  "golang"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status Geral & Métricas Obrigatórias",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Disponibilidade do Serviço (Requisito Obrigatório)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_availability", "legendFormat": "Disponibilidade" }
   ]
  },
  {
   "title": "Volume Total de Requisições (Requisito Obrigatório)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total) or vector(0)",
     "legendFormat": "Total de Requisições"
    }
   ]
  },
  {
   "title": "Requisições por Código de Retorno HTTP",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Comportamento Temporal e Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Throughput (Requisições por Segundo - RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (endpoint, status)",
     "legendFormat": "{{endpoint}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Tempo Médio de Resposta (Latência)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "Latência Média"
    }
   ]
  }
 ]
}