global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "http-server-projeto-korp"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["http-server-projeto-korp:8080"]
        labels:
          app: "http-server-projeto-korp"
          env: "production"
